<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="EsoData.NET" Version="1.1.0" Condition="'$(UseLocalEsoData)' != 'true'" />
    <ProjectReference Include="../../../EsoData.NET/src/EsoData/EsoData.csproj" Condition="'$(UseLocalEsoData)' == 'true'" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>
</Project>
